config/routes.rb
Rails.application.routes.draw do

  get '/contents/:section' => 'contents#section'
  get '/initials/:id' => 'initials#show', as: :initial
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  get '/pages/:id' => 'pages#show'
  resources :mango_pay_accounts, only: [:new, :create]
  resources :bank_accounts, only: [:new, :create]
  resources :payments, only: [:new, :create]
  get '/stripe_accounts/callback' => 'stripe_accounts#callback'

  resources :searches, only: [:index] do
    collection do
      get :get_distances
    end
  end
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :restore
      post :reply
      post :mark_as_read
    end

    collection do
      delete :empty_trash
    end
  end
  resources :images, only: [:show]
  resources :users, only: [:show]
  resources :reservations, only: [:create] do
    member do
      get :request_payment
      post :pay
      post :accept
      post :reject
    end
  end
  resources :listings, only: [:show, :edit, :update, :new, :create, :destroy]
  get '/dashboard' => 'dashboard#index'
  get '/change_locale/:locale' => 'root#change_locale', as: :change_locale
  root 'root#index'

  get '/how_it_works' => 'pages#how_it_works'
  get '/faq' => 'pages#faq'
  get '/trust_and_safety' => 'pages#trust_and_safety'
  get '/about_us' => 'pages#about_us'
  get '/privacy_policy' => 'pages#privacy_policy'
  get '/terms_of_use' => 'pages#terms_of_use'
  get '/contact_us' => 'pages#contact_us'
  get '/promotion_fb' => 'pages#promotion_fb'

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]
  before_action :get_box, only: [:index]
  before_action :check_reservation_paid, only: [:reply]

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    respond_with(@conversation, location: conversation_path)
  end

  def show
    if !@conversation.is_participant?(current_user)
      redirect_to root_path, flash: {error: t("flash.unauthorized")}
    end
  end

  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end

    @conversations = @mailbox.conversations

    @conversations = @conversations.page(params[:page]).per(15)
  end

  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end

  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end

  private
    def check_reservation_paid
      conversation = get_conversation
      originator = conversation.originator

      if (reservation = originator).is_a?(Reservation)
        if !reservation.paid?
          redirect_to conversation_path(conversation), flash: {error: t("conversation.not_paid_yet")}
        end
      end
    end

    def get_box
      if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
        params[:box] = 'inbox'
      end
      @box = params[:box]
    end

    def get_conversation
      @conversation ||= @mailbox.conversations.find(params[:id])
    end

    def get_mailbox
      @mailbox ||= current_user.mailbox
    end
end

app/views/conversations/index.html.erb
<div class="inbox row">
  <div class="small-12 column">
    <h1><%= t("inbox.title") %></h1>

    <% if @conversations.empty? %>

    <div class="alert-box radius info">
      <p><%= t("inbox.no_messages")%> </p>
    </div>

    <% else %>
      <%= cell('conversation', collection: @conversations, current_user: current_user) %>

      <%= paginate @conversations %>
    <% end %>
  </div>
</div>

app/views/conversations/show.html.erb
<div class="inbox row">
  <div class="small-12 column">
    <h1><%= link_to t("inbox.title"), conversations_path %></h1>

    <div>
      <h5><%= @conversation.reservation.listing.name %></h5>
      <div>
        <%= image_tag image_path(@conversation.reservation.listing.image_data), style: 'max-width: 200px' %>
      </div>
      <h6><%= l @conversation.reservation.start_date, format: :long %> - 
      <%= l @conversation.reservation.end_date, format: :long %></h6>
    </div>

    <%= form_tag reply_conversation_path(@conversation) do %>
      <textarea placeholder="..." required name="body"></textarea>
      <input type="submit" value="<%= t("inbox.submit") %>" class="button round">
    <% end %>

    <%= cell('message', collection: @conversation.messages.order("id DESC"), current_user: current_user) %>
  </div>
</div>