config/routes.rb
Rails.application.routes.draw do

  get '/contents/:section' => 'contents#section'
  get '/initials/:id' => 'initials#show', as: :initial
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  get '/pages/:id' => 'pages#show'
  resources :mango_pay_accounts, only: [:new, :create]
  resources :bank_accounts, only: [:new, :create]
  resources :payments, only: [:new, :create]
  get '/stripe_accounts/callback' => 'stripe_accounts#callback'

  resources :searches, only: [:index] do
    collection do
      get :get_distances
    end
  end
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :restore
      post :reply
      post :mark_as_read
    end

    collection do
      delete :empty_trash
    end
  end
  resources :images, only: [:show]
  resources :users, only: [:show]
  resources :reservations, only: [:create] do
    member do
      get :request_payment
      post :pay
      post :accept
      post :reject
    end
  end
  resources :listings, only: [:show, :edit, :update, :new, :create, :destroy]
  get '/dashboard' => 'dashboard#index'
  get '/change_locale/:locale' => 'root#change_locale', as: :change_locale
  root 'root#index'

  get '/how_it_works' => 'pages#how_it_works'
  get '/faq' => 'pages#faq'
  get '/trust_and_safety' => 'pages#trust_and_safety'
  get '/about_us' => 'pages#about_us'
  get '/privacy_policy' => 'pages#privacy_policy'
  get '/terms_of_use' => 'pages#terms_of_use'
  get '/contact_us' => 'pages#contact_us'
  get '/promotion_fb' => 'pages#promotion_fb'

end

app/views/user_notifier/listing_created.html.erb
<p><%= I18n.t("mailers.user_notifier.listing_created.phrase_1") %></p>
<p><%= raw(I18n.t("mailers.user_notifier.listing_created.phrase_2",
	link: link_to(t('global.click_here'), listing_url(@listing)))) %></p>

app/views/user_notifier/listing_created.text.erb
<%= I18n.t("mailers.user_notifier.listing_created.phrase_1") %>
<%= raw(I18n.t("mailers.user_notifier.listing_created.phrase_2",
	link: link_to(t('global.click_here'), listing_url(@listing)))) %>

app/views/user_notifier/signup.html.erb
<%= I18n.t("mailers.user_notifier.signup.body", user: @user.name) %>

app/views/user_notifier/signup.text.erb
<%= I18n.t("mailers.user_notifier.signup.body", user: @user.name) %>