config/routes.rb
Rails.application.routes.draw do

  get '/contents/:section' => 'contents#section'
  get '/initials/:id' => 'initials#show', as: :initial
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

  get '/pages/:id' => 'pages#show'
  resources :mango_pay_accounts, only: [:new, :create]
  resources :bank_accounts, only: [:new, :create]
  resources :payments, only: [:new, :create]
  get '/stripe_accounts/callback' => 'stripe_accounts#callback'

  resources :searches, only: [:index] do
    collection do
      get :get_distances
    end
  end
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :restore
      post :reply
      post :mark_as_read
    end

    collection do
      delete :empty_trash
    end
  end
  resources :images, only: [:show]
  resources :users, only: [:show]
  resources :reservations, only: [:create] do
    member do
      get :request_payment
      post :pay
      post :accept
      post :reject
    end
  end
  resources :listings, only: [:show, :edit, :update, :new, :create, :destroy]
  get '/dashboard' => 'dashboard#index'
  get '/change_locale/:locale' => 'root#change_locale', as: :change_locale
  root 'root#index'

  get '/how_it_works' => 'pages#how_it_works'
  get '/faq' => 'pages#faq'
  get '/trust_and_safety' => 'pages#trust_and_safety'
  get '/about_us' => 'pages#about_us'
  get '/privacy_policy' => 'pages#privacy_policy'
  get '/terms_of_use' => 'pages#terms_of_use'
  get '/contact_us' => 'pages#contact_us'
  get '/promotion_fb' => 'pages#promotion_fb'

end

app/models/search.rb
require 'ostruct'

class Search < OpenStruct
  def initialize options
    if options[:start_date].blank? || options[:end_date].blank?
      options[:start_date] = options[:end_date] = nil
    end

    if options[:lat].blank? || options[:lng].blank?
      options[:lat] = options[:lng] = nil
    end

    super(options)
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  respond_to :json, only: [:get_distances]
  def index
    @search = Search.new(search_params)
    @listings = SearchListingsContext.new(@search).call
  end

  def get_distances
    @result = if params[:lng] && params[:lat]
      longitude = Float(params[:lng])
      latitude = Float(params[:lat])

      locations = ListingLocation.
        limit(10_000). # mongoid forces to use a limit
        geo_near([longitude, latitude]).
        distance_multiplier(6378.1).
        spherical.
        unique

      locations
    else
      Listing.none
    end

    respond_with(locations)
  end

  private
    def search_params
      params[:search] ||= {somethingtopasstherequire: 'x'}
      params.require(:search).permit(:q, :lat, :lng, :start_date, :end_date, :address)
    end
end

app/views/searches/index.html.erb
<!-- <script src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script> -->

<main>
  <div class="search-pane">
  	<div id="map">
  	</div>
  </div>

  <div class="search-pane pane-content">

    <h2 class="inline-block">
      <i class="fa fa-search"></i>
      <% if @search.q.present? %>
        <%= t("search.title", item: @search.q) %>
      <% else %>
        <%= t("search.title_empty") %>
      <% end %>
    </h2>

    <%= render partial: 'root/search_form' %>

    <ul class="search-results">
      <% @listings.each do |listing| %>
      <li>
        <div class="card-product">
          <%= link_to listing_path(listing) do %>
            <div class="product">
              <%= image_tag image_path(listing.image_data) %>
              <div class="gradient"></div>
              <div class="caption">
                <span class="product-name"><%= listing.name %></span>
                <span class="product-info">
                  <%= number_to_currency listing.daily_price %>
                  &bullet;
                  <%= listing.user.name %>
                </span>
              </div>
            </div>
          <% end %>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</main>

<div class="clear"></div>

<script type="x-template" name="infowindow">
  <div class="infowindow">
    <a href="{{item_url}}" target="_blank" style="background-image: url('{{image_url}}')">

      <div class="card-footer">
        <p class="item-name">
          {{item_name}}
        </p>
        <p class="prices">
          {{prices}}
        </p>
      </div>
    </a>
  </div>
</script>

<script>
  var infowindows = [];
	var map = new google.maps.Map(document.getElementById('map'), {
		center: {lat: <%= @search.lat || 40.4169473 %>, lng: <%= @search.lng || -3.7057225 %>},
		scrollwheel: true,
		zoom: 14
	});

  var markers = [];
  <% @listings.each do |listing| %>
    var listingJson = {itemName: '<%= listing.name %>',
      itemUrl: '<%= listing_path(listing) %>',
      imageUrl: '<%= image_path(listing.image_data) %>',
      prices: '<%= t("listings.new.cost_per_day") %>: <%= number_to_currency(listing.daily_price) %><br/> \
      <%= t("listings.new.cost_per_week") %>: <%= number_to_currency(listing.weekly_price) %>'
    };

    markers.push(
      buildMarker({
        position: {lat: <%= listing.lat %>, lng: <%= listing.lng %>},
        title: '<%= listing.name %>'
      }, listingJson));
  <% end %>

  <% if @search.lat.blank? || @search.lng.blank? %>
    var bounds = new google.maps.LatLngBounds();
    for(i=0;i<markers.length;i++) {
      bounds.extend(markers[i].getPosition());
    }

    if(!bounds.isEmpty()){
      map.fitBounds(bounds);
    }
  <% end %>

  if(markers.length > 0){
    var markerCluster = new MarkerClusterer(map, markers);
  }

  function buildMarker(options, listingJson){
    var marker = new google.maps.Marker(options);
    var content = buildInfowindowContent(listingJson);

    var infowindow = new google.maps.InfoWindow({
        content: content
    });
    infowindows.push(infowindow);
    infowindow.opened = false;

    infowindow.toggle = function(){
        for(var i = 0;i<infowindows.length;i++){
            var iw = infowindows[i];
            if(iw != this){
                iw.opened = false;
                iw.close();
            }
        }
        if(this.opened){
            this.close(map, marker);
        }else{
            this.open(map, marker);
        }
        this.opened = !this.opened;
    };

    google.maps.event.addListener(marker, 'click', function(e,i) {
      infowindow.toggle();
    });

    google.maps.event.addListener(marker, 'mouseover', function(e,i) {
      infowindow.open(map, marker);
    });

    /*google.maps.event.addListener(marker, 'mouseout', function(e,i) {
      infowindow.close(map, marker);
    });*/

    return marker;
  }

  function buildInfowindowContent(data){
    var template = jQuery("script[type='x-template'][name='infowindow']").html();
    template = template.replace("{{item_url}}", data.itemUrl);
    template = template.replace("{{image_url}}", data.imageUrl);
    template = template.replace("{{item_name}}", data.itemName);
    template = template.replace("{{prices}}", data.prices);

    return template;
  }
</script>